from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest


def _load_yaml(path: Path) -> dict[str, Any]:
    try:
        import yaml  # type: ignore
    except Exception as e:  # pragma: no cover
        pytest.skip(f"PyYAML not available: {e}")
    if not path.exists():
        # default: enable all tests
        return {
            'multisite': {'single_isotopes': True, 'three_isotopes': True},
            'powder': {'freq': True, 'field': True},
            'fit': {'multisite': True, 'powder': True},
            'vary': {'freq_vs_field': True, 'elevels_vs_field': True, 'freq_vs_eta': True, 'freq_vs_angle': True},
            'freq': {'multisite_ed': True},
            'freq_fit': {'multisite': True},
            'field_spec': {'multisite': True},
            'field_fit': {'multisite': True},
            'freq_powder': {'modern': True},
            'freq_powder_fit': {'modern': True},
            'field_powder': {'modern': True},
            'field_powder_fit': {'modern': True},
        }
    import yaml  # type: ignore
    with open(path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f) or {}


def pytest_addoption(parser: pytest.Parser) -> None:
    parser.addoption(
        "--test-config",
        action="store",
        default=str(Path("tests/test_config.yaml").resolve()),
        help="Path to YAML test configuration with booleans to enable/disable tests.",
    )
    parser.addoption(
        "--verbose-plots",
        action="store_true",
        default=False,
        help="Persist plots and generated data under tests/generated_data (or a custom path) for later inspection.",
    )
    parser.addoption(
        "--artifacts-dir",
        action="store",
        default=str(Path("tests/generated_data").resolve()),
        help="Directory to persist generated outputs (plots, data). Defaults to tests/generated_data.",
    )


def pytest_configure(config: pytest.Config) -> None:
    config.addinivalue_line("markers", "cfg(path): test requires config path boolean to be True")


def _resolve_path(d: dict[str, Any], path: str) -> bool:
    cur: Any = d
    for key in path.split('.'):
        if not isinstance(cur, dict) or key not in cur:
            return True  # default to enabled if unknown
        cur = cur[key]
    return bool(cur)


def pytest_collection_modifyitems(config: pytest.Config, items: list[pytest.Item]) -> None:
    cfg_path = Path(config.getoption("--test-config"))
    cfg = _load_yaml(cfg_path)
    selected: list[pytest.Item] = []
    deselected: list[pytest.Item] = []
    for item in items:
        mark = item.get_closest_marker("cfg")
        if mark:
            paths = list(mark.args)
            enabled = all(_resolve_path(cfg, p) for p in paths)
            if not enabled:
                deselected.append(item)
                continue
        selected.append(item)
    if deselected:
        config.hook.pytest_deselected(items=deselected)
        items[:] = selected


def _gen_gaussian(x, mu, sigma, amp=1.0):
    import numpy as _np
    return amp * _np.exp(-0.5 * ((x - mu) / sigma) ** 2)


def _write_noisy_two_column(out: Path, x, y, header_lines: int = 0) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    for _ in range(header_lines):
        lines.append("# generated by tests\n")
    # space-delimited
    for xi, yi in zip(x, y):
        lines.append(f"{xi:.8f} {yi:.8f}\n")
    out.write_text(''.join(lines), encoding='utf-8')


def pytest_sessionstart(session: pytest.Session) -> None:
    # Optionally persist artifacts and generate deterministic noisy datasets
    config = session.config
    verbose_plots = bool(config.getoption("--verbose-plots"))
    base_dir = Path(config.getoption("--artifacts-dir")).resolve()
    base_dir.mkdir(parents=True, exist_ok=True)

    # Expose artifacts dir to tests via env var when requested
    if verbose_plots:
        os = __import__('os')
        os.environ['PY_SIMNMR_TEST_ARTIFACTS'] = str(base_dir)

    # Always generate test datasets in a predictable place
    data_dir = base_dir

    import numpy as np
    rng = np.random.default_rng(20250903)

    # Dataset 1: frequency fit (75As) - two columns, no headers
    x1 = np.linspace(20.0, 55.0, 1000)
    y1 = (
        _gen_gaussian(x1, mu=25.0, sigma=0.25, amp=0.6)
        + _gen_gaussian(x1, mu=30.5, sigma=0.35, amp=0.8)
        + _gen_gaussian(x1, mu=40.0, sigma=0.45, amp=0.5)
    )
    y1 += rng.normal(0, 0.02, size=x1.shape)
    f1 = data_dir / "fit_test_75As_vc=11p1MHz_H=5T_f=20-55MHz_FWHM=0p4MHz_vQFWHM=0p1MHz_noisy.txt"
    _write_noisy_two_column(f1, x1, y1, header_lines=0)

    # Dataset 2: powder fit - two columns, 30 header lines
    x2 = np.linspace(75.0, 77.0, 200)
    y2 = _gen_gaussian(x2, mu=76.0, sigma=0.2, amp=1.0)
    y2 += rng.normal(0, 0.01, size=x2.shape)
    f2 = data_dir / "plot_freq_powder_spectrum_test_data_pp_noisy.txt"
    _write_noisy_two_column(f2, x2, y2, header_lines=30)

    # Dataset 3: field fit/powder fit - two columns, no headers
    x3 = np.linspace(0.5, 1.5, 300)
    y3 = _gen_gaussian(x3, mu=1.0, sigma=0.1, amp=1.0)
    y3 += rng.normal(0, 0.01, size=x3.shape)
    f3 = data_dir / "field_fit_multisite_data.txt"
    _write_noisy_two_column(f3, x3, y3, header_lines=0)

    # Expose paths via env so tests can pick them up
    os = __import__('os')
    os.environ['PY_SIMNMR_TEST_FREQ_FIT_DATA'] = str(f1)
    os.environ['PY_SIMNMR_TEST_POWDER_FIT_DATA'] = str(f2)
    os.environ['PY_SIMNMR_TEST_FIELD_FIT_DATA'] = str(f3)
    os.environ['PY_SIMNMR_TEST_FIELD_POWDER_FIT_DATA'] = str(f3)
