"""Single-site config for `nmr-field-spec` smoke tests."""

CONFIG = {
    'isotope_list': ['75As'],
    'site_multiplicity_list': [1.0],
    'Ka_list': [0.1],
    'Kb_list': [0.1],
    'Kc_list': [0.1],
    'vc_list': [8.5],
    'eta_list': [0.15],
    'va_list': [None],
    'vb_list': [None],
    'Hinta_list': [0.0],
    'Hintb_list': [0.0],
    'Hintc_list': [0.0],
    'phi_z_deg_list': [0.0],
    'theta_x_prime_deg_list': [90.0],
    'psi_z_prime_deg_list': [0.0],
    'sim_type': 'exact diag',
    'f0': 45.0,
    'min_field': 0.5,
    'max_field': 1.5,
    'n_field_points': 256,
    'convolution_function_list': ['gauss'],
    'conv_FWHM_list': [0.01],
    'conv_vQ_FWHM_list': [0.005],
    'mtx_elem_min': 0.15,
    'plot_individual_bool': False,
    'plot_sum_bool': True,
    'plot_legend_width_ratio': [3.25, 1.0],
    'x_axis_min': 0.5,
    'x_axis_max': 1.5,
    'sim_export_file': '',
}
